# Financial Data Chatbot Development

This notebook demonstrates the development of a simple chatbot that provides financial information for selected companies based on user queries. The chatbot uses a pandas DataFrame to retrieve and process financial data for companies such as Apple, Microsoft, and Tesla.

In [2]:
import pandas as pd

## Data Loading and Preprocessing

We begin by loading the financial data into a pandas DataFrame. The data includes key financial metrics for companies like Apple, Microsoft, and Tesla over the years 2021, 2022, and 2023.

In [3]:
df  = pd.read_csv('data_transform.csv',)

In [4]:
df.head()

,Year,Company,Total revenue,Net income,Total assets,Total liabilities,Cash Flow from Operating Activities,Revenue Growth (%),Net Income Growth (%),Liabilities Change (%),Total Assets Change (%),Profit Margin (%),Return on Assets(%),Shareholder s equity,Return on Equity (%),Asset turnover ratio
0,2021,Apple,365817,94680,351002,287912,104038,NaN,NaN,NaN,NaN,25.881793,26.974205,63090,150.071327,1.042208
1,2021,Microsoft,198270,72738,364840,198298,89035,NaN,NaN,NaN,NaN,36.686337,19.936959,166542,43.675469,0.543444
2,2021,Tesla,53823,5644,62131,30548,5644,NaN,NaN,NaN,NaN,10.486223,9.084032,31583,17.870373,0.866283
3,2022,Apple,394328,99803,352755,302083,122151,7.793788,5.410858,4.921990,0.499427,25.309641,28.292441,50672,196.958873,1.117852
4,2022,Microsoft,211915,72361,411976,205753,87582,6.882030,-0.518299,3.759493,12.919636,34.146238,17.564373,206223,35.088715,0.514387

## Function Definitions

We define a function to handle user queries and retrieve relevant financial data from the DataFrame.

In [47]:
def get_inquiries(user_input):
    company = []
    if "apple" in user_input:
        company.append("Apple")
    if "microsoft" in user_input:
        company.append("Microsoft")
    if "tesla" in user_input:
        company.append("Tesla")

    year = []
    if "between 2021 and 2023" in user_input:
        year.extend(["2021", "2022", "2023"])
    elif "2021" in user_input:
        year.append("2021")
    elif "2022" in user_input:
        year.append("2022")
    elif "2023" in user_input:
        year.append("2023")
    
    
    info_type = []
    if "total revenue" in user_input:
        info_type.append("Total revenue")
    if "net income" in user_input or "total income" in user_input:
        info_type.append("Net income")
    if "total assets" in user_input:
        info_type.append("Total assets")
    if "total liabilities" in user_input:
        info_type.append("Total liabilities")
    if "cash flow from operating activities" in user_input:
        info_type.append("Cash Flow from Operating Activities")
    if "revenue growth" in user_input:
        info_type.append("Revenue Growth (%)")
    if "net income growth" in user_input:
        info_type.append("Net Income Growth (%)")
    if "liabilities change" in user_input:
        info_type.append("Liabilities Change (%)")
    if "total assets change" in user_input:
        info_type.append("Total Assets Change (%)")
    if "profit margin" in user_input:
        info_type.append("Profit Margin (%)")
    if "return on assets" in user_input:
        info_type.append("Return on Assets (%)")
    if "shareholder equity" in user_input or "shareholders equity" in user_input:
        info_type.append("Shareholder's Equity")
    if "return on equity" in user_input:
        info_type.append("Return on Equity (%)")
    if "asset turnover ratio" in user_input:
        info_type.append("Asset Turnover Ratio")
    
    return company, year, info_type

## Chatbot Logic

Rule-based logic implementation are used in chatbot development. The chatbot processes the user's input, determines the company, year, and type of financial information requested, and then retrieves the relevant data from the DataFrame.

In [48]:
def response(company,year, info_type):
    if len(company) == 0:
        print("Please indicate company you are interested in.")
    
    static_inf = ["Total revenue","Net income","Total assets","Total liabilities","Cash Flow from Operating Activities"]
    dynamic_inf = ["Revenue Growth (%)","Net Income Growth (%)","Liabilities Change (%)","Total Assets Change (%)",
                   "Profit Margin (%)","Return on Assets (%)","Shareholder s Equity","Return on Equity (%)","Asset Turnover Ratio"]
    

    for comp in company:
        if len(year) == 0:
            for y in ["2021","2022","2023"]:
                for inf in info_type:
                    result = df[(df['Company']==comp) & (df['Year'] == int(y))]
                    print(f"The {inf} of {comp} in {y} incresed by {result[inf].values[0]:.2f}%")
        else:
            for y in year:
                for inf in info_type:
                    result = df[(df['Company']==comp) & (df['Year'] == int(y))]
                    
                    if inf in static_inf:
                        print(f"The {inf} of {comp} in {y} was {result[inf].values[0]:.2f} million.")
                    elif inf in dynamic_inf:
                        print(f"{inf} by {result[inf].values[0]:.2f}% compared to the previous year.")

In [ ]:
def chatbot():
    print("Welcome to the Financial Chatbot! How can I help you today?")
    
    user_input = input("Please enter your query: ").strip().lower()

    company,year, info_type = get_inquiries(user_input)

    response(company,year, info_type)

    
    

if __name__ == "__main__":
    chatbot()

## Conclusion

This notebook demonstrates a basic implementation of a financial data chatbot using Rule-based logic. Future improvements could include more sophisticated natural language processing to handle a wider variety of user queries and connecting to live financial data sources for real-time updates.